spring.application.name=txnm-auth-service
server.port=8383

spring.profiles.active=dev

# JWT Configuration
jwt.secret=your-256-bit-secret-key-base64-encoded-make-it-very-long-and-secure
jwt.expiration=86400000  # 24 hours in milliseconds